import { createRouter, createWebHistory } from 'vue-router'
const routes = [
    { path: '/', redirect: '/shouye' },
    { path: '/shouye', name: 'ShouYe', component: () => import('../views/Main.vue') },
    { path: '/faxian', name: 'FaXian', component: () => import('../views/FaXian.vue') },
    { path: '/message', name: 'Message', component: () => import('../views/Message.vue') },
    { path: '/myself', name: 'MySelf', component: () => import('../views/MySelf.vue') },
    { path: '/article', name: 'ArticleDetail', component: () => import('../views/shouye_pages/ArticleDetail.vue') },
    { path: '/tags', name: 'TagList', component: () => import('../views/faxian_pages/tags/TagList.vue') },
    { path: '/tag', name: 'TagArticles', component: () => import('../views/faxian_pages/tags/TagArticles.vue') },
    { path: '/category', name: 'CategoryArticles', component: () => import('../views/faxian_pages/categories/CategoryArticles.vue') },
    { path: '/category-detail', name: 'CategoryDetail', component: () => import('../views/faxian_pages/categories/CategoryDetail.vue') },
    { path: '/rankings', name: 'Rankings', component: () => import('../views/faxian_pages/rankings/Rankings.vue') },
    { path: '/search', name: 'Search', component: () => import('../views/shouye_pages/search/Search.vue') },
    { path: '/search-result', name: 'SearchResult', component: () => import('../views/shouye_pages/search/SearchResult.vue') },
    { path: '/chat', name: 'ChatDetail', component: () => import('../views/message_pages/chat/ChatDetail.vue') },
    { path: '/system-notice', name: 'SystemNotice', component: () => import('../views/message_pages/SystemNotice.vue') },
    { path: '/profile', name: 'UserProfile', component: () => import('../views/myself_pages/profile/UserProfile.vue') },
    { path: '/settings', name: 'Settings', component: () => import('../views/myself_pages/settings/Settings.vue') },
    { path: '/settings-page', name: 'SettingsPage', component: () => import('../views/myself_pages/settings/SettingsPage.vue') },
    { path: '/security', name: 'Security', component: () => import('../views/myself_pages/settings/Security.vue') },
    { path: '/about', name: 'About', component: () => import('../views/myself_pages/settings/About.vue') },
    { path: '/following', name: 'Following', component: () => import('../views/myself_pages/social/Following.vue') },
    { path: '/followers', name: 'Followers', component: () => import('../views/myself_pages/social/Followers.vue') },
    { path: '/follow-list', name: 'FollowList', component: () => import('../views/myself_pages/social/FollowList.vue') },
    { path: '/my-articles', name: 'MyArticles', component: () => import('../views/myself_pages/content/MyArticles.vue') },
    { path: '/my-questions', name: 'MyQuestions', component: () => import('../views/myself_pages/content/MyQuestions.vue') },
    { path: '/favorites', name: 'Favorites', component: () => import('../views/myself_pages/content/Favorites.vue') },
    { path: '/my-favorites', name: 'MyFavorites', component: () => import('../views/myself_pages/content/MyFavorites.vue') },
    { path: '/history', name: 'History', component: () => import('../views/myself_pages/content/History.vue') },
    { path: '/question', name: 'QuestionDetail', component: () => import('../views/shouye_pages/ArticleDetail.vue') },
    { path: '/privacy', name: 'Privacy', component: () => import('../views/myself_pages/settings/About.vue') },
    { path: '/notification-settings', name: 'NotificationSettings', component: () => import('../views/myself_pages/settings/Settings.vue') },
    { path: '/post-edit', name: 'PostEdit', component: () => import('../views/faxian_pages/PostEdit.vue') },
    { path: '/login', name: 'Login', component: () => import('../views/myself_pages/auth/Login.vue') },
    { path: '/register', name: 'Register', component: () => import('../views/myself_pages/auth/Register.vue') }
]
const router = createRouter({ history: createWebHistory(), routes })
export default router
